<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Reporter\Data\" />
    <Folder Include="Areas\Reporter\Models\" />
    <Folder Include="wwwroot\AdminTemplate\app-assets\vendors\css\tables\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.33" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.33">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.33" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.33" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.33">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.17" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewsWebSite.Application\NewsWebSite.Application.csproj" />
    <ProjectReference Include="..\NewsWebSite.Common\NewsWebSite.Common.csproj" />
    <ProjectReference Include="..\NewsWebSite.Persistence\NewsWebSite.Persistence.csproj" />
  </ItemGroup>

</Project>
